# Site
name: "'UnRead' Gems | 'చదవని'ముత్యాలు"
title: "'UnRead' Gems | 'చదవని'ముత్యాలు"
description: "Chance to redeem yourself by reading through these super long WhatsApp forwards"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /uncle-tales
google_analytics: 'UA-111600714-1'
# disqus: 'demowebsite'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  author-1:
    name: Sal
    display_name: తోట రాముడు
    avatar: 'assets/images/author-1.png'
    #email: wowthemesnet@gmail.com
    #web: https://www.wowthemes.net
    #twitter: https://twitter.com/wowthemesnet
    description: "రంగు పడుద్ది"
  author-2:
    name: chanti
    display_name: చంటిగాడు 
    avatar: 'assets/images/author-2.png'
    #email: wowthemesnet@gmail.com
    #web: https://www.wowthemes.net
    #twitter: https://twitter.com/wowthemesnet
    description: "చంటిగాడు local"
  author-3:
    name: Mr. Bing
    display_name: Chandler Bing 
    avatar: 'assets/images/author-3.png'
    #email: wowthemesnet@gmail.com
    #web: https://www.wowthemes.net
    #twitter: https://twitter.com/wowthemesnet
    description: "Your funny man"
  author-4:
    name: Mrs. Green
    display_name: Rachel Green
    avatar: 'assets/images/author-4.png'
    #email: wowthemesnet@gmail.com
    #web: https://www.wowthemes.net
    #twitter: https://twitter.com/wowthemesnet
    description: "The indecisive damsel"
  SP:
    name: SP
    display_name: Satya Pavan    
    avatar: 'assets/images/author-sp.png'
    #email: wowthemesnet@gmail.com
    web: https://satyapavan.github.io/
    #twitter: https://twitter.com/wowthemesnet
    description: "I built the internet"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 9
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
# adsense-data-ad-client: "ca-pub-3412143450191416"
# adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
